name: Kyverno Policy Tests

on:
  pull_request:
    branches:
      - main

jobs:
  kyverno-test:
    name: Run Kyverno policy tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Install Kyverno CLI
        run: |
          curl -L https://github.com/kyverno/kyverno/releases/latest/download/kyverno-cli_v1.12.5_linux_x86_64.tar.gz -o kyverno.tar.gz
          tar -xvf kyverno.tar.gz
          sudo mv kyverno /usr/local/bin/

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Verify tools
        run: |
          helm version
          kyverno version
          yq --version

      - name: Run Kyverno tests
        run: |
          chmod +x test.sh
          ./test.sh
