name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write   # needed to push to GHCR

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      HELM_EXPERIMENTAL_OCI: "1"
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: helm
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-github-labels: true

  publish-chart:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Verify Helm Version
        run: helm version

      - name: Helm lint
        run: helm lint .

      - name: Helm dependency update
        run: helm dependency update

      - name: Package Helm chart
        run: helm package .

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Push Helm chart as OCI artifact
        run: |
          CHART_FILE=$(ls *.tgz)
          helm push "$CHART_FILE" oci://ghcr.io/${{ github.repository_owner }}/helm-charts

      - name: Upload chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: "*.tgz"
